drinks/urls.py
from django.urls import path
from drinks.views import *
app_name='drinks'

urlpatterns=[
    path('bindu/',bindu,name='bindu'),
    path('maaza/',maaza,name='maaza'),
]

food/urls.py
from django.urls import path
from food.views import *
app_name='food'

urlpatterns=[
    path('chicken/',chicken,name='chicken'),
    path('curd/',curd,name='curd'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import food,drinks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('drinks/',include('drinks.urls')),
]

drinks/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

drinks/views.py
from django.shortcuts import render

# Create your views here.
def bindu(request):
    return render(request,'bindu.html')

def maaza(request):
    return render(request,'maaza.html')

food/views.py
from django.shortcuts import render

# Create your views here.
def chicken(request):
    return render(request,'chicken.html')


def curd(request):
    return render(request,'curd.html')

templates/bindu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>drink bindu after eating chicken</h1>
        <h1><a href = '{% url "food:chicken" %}'> chicken</a></h1>
        <h1><a href = '{% url "drinks:maaza" %}'> maaza</a></h1>
        <h1><a href ='{% url "food:curd" %}'> curd</a></h1>
    </center>
    
</body>
</html>

templates/chicken.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            i like chicken
        </h1>
        <h1><a href = '{% url "food:curd" %}'> curd</a></h1>
        <h1><a href = '{% url "drinks:maaza" %}'> maaza</a></h1>
        <h1><a href ='{% url "drinks:bindu" %}'> bindu</a></h1>
    </center>
</body>
</html>

templates/curd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>eat curd along with chicken</h1>
        <h1>
            i like chicken
        </h1>
        <h1><a href = '{% url "food:chicken" %}'> chicken</a></h1>
        <h1><a href = '{% url "drinks:maaza" %}'> maaza</a></h1>
        <h1><a href ='{% url "drinks:bindu" %}'> bindu</a></h1>
    </center>
</body>
</html>

templates/maaza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
          drink maaza after sometime  
        </h1>
      
        <h1><a href = '{% url "food:curd" %}'> curd</a></h1>
        <h1><a href = '{% url "food:chicken" %}'>chicken</a></h1>
        <h1><a href ='{% url "drinks:bindu" %}'> bindu</a></h1>
    </center>
</body>
</html>